package vo;

import oracle.jbo.server.ViewObjectImpl;

import vo.common.EvoLpSctView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 17:21:36 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EvoLpSctViewImpl extends ViewObjectImpl implements EvoLpSctView {
    /**
     * This is the default constructor (do not remove).
     */
    public EvoLpSctViewImpl() {
    }

    public void url(String cpgId) {
    }

}
