package vo;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 08 20:33:36 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FeedbackTipoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Descripcion {
            public Object get(FeedbackTipoRowImpl obj) {
                return obj.getDescripcion();
            }

            public void put(FeedbackTipoRowImpl obj, Object value) {
                obj.setDescripcion((String)value);
            }
        }
        ,
        Codigo {
            public Object get(FeedbackTipoRowImpl obj) {
                return obj.getCodigo();
            }

            public void put(FeedbackTipoRowImpl obj, Object value) {
                obj.setCodigo((String)value);
            }
        }
        ,
        SbpSlsGestFeedbackView1 {
            public Object get(FeedbackTipoRowImpl obj) {
                return obj.getSbpSlsGestFeedbackView1();
            }

            public void put(FeedbackTipoRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FeedbackTipo1 {
            public Object get(FeedbackTipoRowImpl obj) {
                return obj.getFeedbackTipo1();
            }

            public void put(FeedbackTipoRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FeedbackTipoRowImpl object);

        public abstract void put(FeedbackTipoRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int CODIGO = AttributesEnum.Codigo.index();
    public static final int SBPSLSGESTFEEDBACKVIEW1 = AttributesEnum.SbpSlsGestFeedbackView1.index();
    public static final int FEEDBACKTIPO1 = AttributesEnum.FeedbackTipo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FeedbackTipoRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Descripcion.
     * @return the Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Descripcion.
     * @param value value to set the  Descripcion
     */
    public void setDescripcion(String value) {
        setAttributeInternal(DESCRIPCION, value);
        System.out.println(value + "DESCRIPTION");
        
    }

    /**
     * Gets the attribute value for the calculated attribute Codigo.
     * @return the Codigo
     */
    public String getCodigo() {
        return (String) getAttributeInternal(CODIGO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Codigo.
     * @param value value to set the  Codigo
     */
    public void setCodigo(String value) {
        setAttributeInternal(CODIGO, value);
        System.out.println(value + "CODIGO");
    }

    /**
     * Gets the view accessor <code>RowSet</code> SbpSlsGestFeedbackView1.
     */
    public RowSet getSbpSlsGestFeedbackView1() {
        return (RowSet)getAttributeInternal(SBPSLSGESTFEEDBACKVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FeedbackTipo1.
     */
    public RowSet getFeedbackTipo1() {
        return (RowSet)getAttributeInternal(FEEDBACKTIPO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
