package vo;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 17 18:24:23 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsDosifXCpgViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsDosifXCpgViewImpl() {
    }
    
    protected void executeQueryForCollection(Object object, Object[] object2, int i) {//para que aparezcan los input text si es que no trae data
                //super.executeQueryForCollection(object, object2, i);
                //if(this.first()==null){
                    Row createRow = this.createRow();
                    this.insertRow(createRow);
                    this.setCurrentRow(createRow);
                //}
        }

}
