package vo;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 17 09:58:18 COT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsUbigeoEvVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        dept {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getdept();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setdept((String)value);
            }
        }
        ,
        codDept {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getcodDept();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setcodDept((String)value);
            }
        }
        ,
        prov {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getprov();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setprov((String)value);
            }
        }
        ,
        codProv {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getcodProv();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setcodProv((String)value);
            }
        }
        ,
        dist {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getdist();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setdist((String)value);
            }
        }
        ,
        codDist {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getcodDist();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setcodDist((String)value);
            }
        }
        ,
        DeptEVVO1 {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getDeptEVVO1();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProvEVVO1 {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getProvEVVO1();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DistEVVO1 {
            public Object get(SbpSlsUbigeoEvVORowImpl obj) {
                return obj.getDistEVVO1();
            }

            public void put(SbpSlsUbigeoEvVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(SbpSlsUbigeoEvVORowImpl object);

        public abstract void put(SbpSlsUbigeoEvVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DEPT = AttributesEnum.dept.index();
    public static final int CODDEPT = AttributesEnum.codDept.index();
    public static final int PROV = AttributesEnum.prov.index();
    public static final int CODPROV = AttributesEnum.codProv.index();
    public static final int DIST = AttributesEnum.dist.index();
    public static final int CODDIST = AttributesEnum.codDist.index();
    public static final int DEPTEVVO1 = AttributesEnum.DeptEVVO1.index();
    public static final int PROVEVVO1 = AttributesEnum.ProvEVVO1.index();
    public static final int DISTEVVO1 = AttributesEnum.DistEVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsUbigeoEvVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute dept.
     * @return the dept
     */
    public String getdept() {
        return (String) getAttributeInternal(DEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute dept.
     * @param value value to set the  dept
     */
    public void setdept(String value) {
        setAttributeInternal(DEPT, value);
        setAttributeInternal(PROV, null);
        setAttributeInternal(DIST, null);
    }

    /**
     * Gets the attribute value for the calculated attribute codDept.
     * @return the codDept
     */
    public String getcodDept() {
        return (String) getAttributeInternal(CODDEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute codDept.
     * @param value value to set the  codDept
     */
    public void setcodDept(String value) {
        setAttributeInternal(CODDEPT, value);
        setAttributeInternal(CODPROV, null);
        setAttributeInternal(CODDIST, null);
    }

    /**
     * Gets the attribute value for the calculated attribute prov.
     * @return the prov
     */
    public String getprov() {
        return (String) getAttributeInternal(PROV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute prov.
     * @param value value to set the  prov
     */
    public void setprov(String value) {
        setAttributeInternal(PROV, value);
        setAttributeInternal(DIST, null);
    }

    /**
     * Gets the attribute value for the calculated attribute codProv.
     * @return the codProv
     */
    public String getcodProv() {
        return (String) getAttributeInternal(CODPROV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute codProv.
     * @param value value to set the  codProv
     */
    public void setcodProv(String value) {
        setAttributeInternal(CODPROV, value);
        setAttributeInternal(CODDIST, null);
    }

    /**
     * Gets the attribute value for the calculated attribute dist.
     * @return the dist
     */
    public String getdist() {
        return (String) getAttributeInternal(DIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute dist.
     * @param value value to set the  dist
     */
    public void setdist(String value) {
        setAttributeInternal(DIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute codDist.
     * @return the codDist
     */
    public String getcodDist() {
        return (String) getAttributeInternal(CODDIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute codDist.
     * @param value value to set the  codDist
     */
    public void setcodDist(String value) {
        setAttributeInternal(CODDIST, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DeptEVVO1.
     */
    public RowSet getDeptEVVO1() {
        return (RowSet)getAttributeInternal(DEPTEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProvEVVO1.
     */
    public RowSet getProvEVVO1() {
        return (RowSet)getAttributeInternal(PROVEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DistEVVO1.
     */
    public RowSet getDistEVVO1() {
        return (RowSet)getAttributeInternal(DISTEVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
