package vo;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 16:44:23 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsCpgPausaViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsCpgPausaViewImpl() {
    }
    
    protected void executeQueryForCollection(Object object, Object[] object2, int i) {
            //super.executeQueryForCollection(object, object2, i);
            //if(this.first()==null){
            Row createRow = this.createRow();
            this.insertRow(createRow);
            this.setCurrentRow(createRow);
            //}
        }

}
