package vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 17:24:31 COT 2017
// ---------------------------------------------------------------------
public interface EvoLpSctView extends ViewObject {
    void url(String cpgId);
}
