package eo;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 21 13:32:53 GMT-05:00 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsCmImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdTabla {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getIdTabla();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setIdTabla((Number)value);
            }
        }
        ,
        IdLote {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getIdLote();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setIdLote((Number)value);
            }
        }
        ,
        IdGrupo {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getIdGrupo();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setIdGrupo((Number)value);
            }
        }
        ,
        FechaCargaS {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getFechaCargaS();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setFechaCargaS((String)value);
            }
        }
        ,
        TipoCarga {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getTipoCarga();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setTipoCarga((String)value);
            }
        }
        ,
        DescripcionCarga {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getDescripcionCarga();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setDescripcionCarga((String)value);
            }
        }
        ,
        IdCargaSbp {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getIdCargaSbp();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setIdCargaSbp((String)value);
            }
        }
        ,
        UsuarioCarga {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getUsuarioCarga();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setUsuarioCarga((String)value);
            }
        }
        ,
        Cantidad {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getCantidad();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setCantidad((String)value);
            }
        }
        ,
        Estado {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getEstado();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setEstado((String)value);
            }
        }
        ,
        FechaCreacion {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getFechaCreacion();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setFechaCreacion((Date)value);
            }
        }
        ,
        Observaciones {
            public Object get(SbpSlsCmImpl obj) {
                return obj.getObservaciones();
            }

            public void put(SbpSlsCmImpl obj, Object value) {
                obj.setObservaciones((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(SbpSlsCmImpl object);

        public abstract void put(SbpSlsCmImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDTABLA = AttributesEnum.IdTabla.index();
    public static final int IDLOTE = AttributesEnum.IdLote.index();
    public static final int IDGRUPO = AttributesEnum.IdGrupo.index();
    public static final int FECHACARGAS = AttributesEnum.FechaCargaS.index();
    public static final int TIPOCARGA = AttributesEnum.TipoCarga.index();
    public static final int DESCRIPCIONCARGA = AttributesEnum.DescripcionCarga.index();
    public static final int IDCARGASBP = AttributesEnum.IdCargaSbp.index();
    public static final int USUARIOCARGA = AttributesEnum.UsuarioCarga.index();
    public static final int CANTIDAD = AttributesEnum.Cantidad.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int FECHACREACION = AttributesEnum.FechaCreacion.index();
    public static final int OBSERVACIONES = AttributesEnum.Observaciones.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsCmImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("eo.SbpSlsCm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IdLote, using the alias name IdLote.
     * @return the IdLote
     */
    public Number getIdLote() {
        return (Number)getAttributeInternal(IDLOTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdLote.
     * @param value value to set the IdLote
     */
    public void setIdLote(Number value) {
        setAttributeInternal(IDLOTE, value);
    }

    /**
     * Gets the attribute value for IdGrupo, using the alias name IdGrupo.
     * @return the IdGrupo
     */
    public Number getIdGrupo() {
        return (Number)getAttributeInternal(IDGRUPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdGrupo.
     * @param value value to set the IdGrupo
     */
    public void setIdGrupo(Number value) {
        setAttributeInternal(IDGRUPO, value);
    }


    /**
     * Gets the attribute value for TipoCarga, using the alias name TipoCarga.
     * @return the TipoCarga
     */
    public String getTipoCarga() {
        return (String)getAttributeInternal(TIPOCARGA);
    }

    /**
     * Sets <code>value</code> as the attribute value for TipoCarga.
     * @param value value to set the TipoCarga
     */
    public void setTipoCarga(String value) {
        setAttributeInternal(TIPOCARGA, value);
    }

    /**
     * Gets the attribute value for IdCargaSbp, using the alias name IdCargaSbp.
     * @return the IdCargaSbp
     */
    public String getIdCargaSbp() {
        return (String)getAttributeInternal(IDCARGASBP);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdCargaSbp.
     * @param value value to set the IdCargaSbp
     */
    public void setIdCargaSbp(String value) {
        setAttributeInternal(IDCARGASBP, value);
    }

    /**
     * Gets the attribute value for UsuarioCarga, using the alias name UsuarioCarga.
     * @return the UsuarioCarga
     */
    public String getUsuarioCarga() {
        return (String)getAttributeInternal(USUARIOCARGA);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsuarioCarga.
     * @param value value to set the UsuarioCarga
     */
    public void setUsuarioCarga(String value) {
        setAttributeInternal(USUARIOCARGA, value);
    }

    /**
     * Gets the attribute value for Cantidad, using the alias name Cantidad.
     * @return the Cantidad
     */
    public String getCantidad() {
        return (String)getAttributeInternal(CANTIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cantidad.
     * @param value value to set the Cantidad
     */
    public void setCantidad(String value) {
        setAttributeInternal(CANTIDAD, value);
    }

    /**
     * Gets the attribute value for Estado, using the alias name Estado.
     * @return the Estado
     */
    public String getEstado() {
        return (String)getAttributeInternal(ESTADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Estado.
     * @param value value to set the Estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**
     * Gets the attribute value for FechaCreacion, using the alias name FechaCreacion.
     * @return the FechaCreacion
     */
    public Date getFechaCreacion() {
        return (Date)getAttributeInternal(FECHACREACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacion.
     * @param value value to set the FechaCreacion
     */
    public void setFechaCreacion(Date value) {
        setAttributeInternal(FECHACREACION, value);
    }


    /**
     * Gets the attribute value for Observaciones, using the alias name Observaciones.
     * @return the Observaciones
     */
    public String getObservaciones() {
        return (String)getAttributeInternal(OBSERVACIONES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Observaciones.
     * @param value value to set the Observaciones
     */
    public void setObservaciones(String value) {
        setAttributeInternal(OBSERVACIONES, value);
    }

    /**
     * Gets the attribute value for FechaCargaS, using the alias name FechaCargaS.
     * @return the FechaCargaS
     */
    public String getFechaCargaS() {
        return (String)getAttributeInternal(FECHACARGAS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCargaS.
     * @param value value to set the FechaCargaS
     */
    public void setFechaCargaS(String value) {
        setAttributeInternal(FECHACARGAS, value);
    }

    /**
     * Gets the attribute value for IdTabla, using the alias name IdTabla.
     * @return the IdTabla
     */
    public Number getIdTabla() {
        return (Number)getAttributeInternal(IDTABLA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdTabla.
     * @param value value to set the IdTabla
     */
    public void setIdTabla(Number value) {
        setAttributeInternal(IDTABLA, value);
    }

    /**
     * Gets the attribute value for DescripcionCarga, using the alias name DescripcionCarga.
     * @return the DescripcionCarga
     */
    public String getDescripcionCarga() {
        return (String)getAttributeInternal(DESCRIPCIONCARGA);
    }

    /**
     * Sets <code>value</code> as the attribute value for DescripcionCarga.
     * @param value value to set the DescripcionCarga
     */
    public void setDescripcionCarga(String value) {
        setAttributeInternal(DESCRIPCIONCARGA, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param idTabla key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idTabla) {
        return new Key(new Object[]{idTabla});
    }


}
