package eo;


import java.sql.SQLException;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;

import utils.CustomEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 23 16:32:26 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsAsigEvXSupImpl extends CustomEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdSup {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getIdSup();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setIdSup((Number)value);
            }
        }
        ,
        NomSup {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getNomSup();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setNomSup((String)value);
            }
        }
        ,
        IdEjVenta {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getIdEjVenta();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setIdEjVenta((Number)value);
            }
        }
        ,
        NomEjVenta {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getNomEjVenta();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setNomEjVenta((String)value);
            }
        }
        ,
        IdCanal {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getIdCanal();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setIdCanal((Number)value);
            }
        }
        ,
        NomCanal {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getNomCanal();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setNomCanal((String)value);
            }
        }
        ,
        Cantidad {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getCantidad();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setCantidad((Number)value);
            }
        }
        ,
        PorcAsig {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getPorcAsig();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setPorcAsig((Number)value);
            }
        }
        ,
        IdTbl {
            public Object get(SbpSlsAsigEvXSupImpl obj) {
                return obj.getIdTbl();
            }

            public void put(SbpSlsAsigEvXSupImpl obj, Object value) {
                obj.setIdTbl((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(SbpSlsAsigEvXSupImpl object);

        public abstract void put(SbpSlsAsigEvXSupImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDSUP = AttributesEnum.IdSup.index();
    public static final int NOMSUP = AttributesEnum.NomSup.index();
    public static final int IDEJVENTA = AttributesEnum.IdEjVenta.index();
    public static final int NOMEJVENTA = AttributesEnum.NomEjVenta.index();
    public static final int IDCANAL = AttributesEnum.IdCanal.index();
    public static final int NOMCANAL = AttributesEnum.NomCanal.index();
    public static final int CANTIDAD = AttributesEnum.Cantidad.index();
    public static final int PORCASIG = AttributesEnum.PorcAsig.index();
    public static final int IDTBL = AttributesEnum.IdTbl.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsAsigEvXSupImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("eo.SbpSlsAsigEvXSup");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IdSup, using the alias name IdSup.
     * @return the IdSup
     */
    public Number getIdSup() {
        return (Number)getAttributeInternal(IDSUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdSup.
     * @param value value to set the IdSup
     */
    public void setIdSup(Number value) {
        setAttributeInternal(IDSUP, value);
    }

    /**
     * Gets the attribute value for NomSup, using the alias name NomSup.
     * @return the NomSup
     */
    public String getNomSup() {
        return (String)getAttributeInternal(NOMSUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for NomSup.
     * @param value value to set the NomSup
     */
    public void setNomSup(String value) {
        setAttributeInternal(NOMSUP, value);
    }

    /**
     * Gets the attribute value for IdEjVenta, using the alias name IdEjVenta.
     * @return the IdEjVenta
     */
    public Number getIdEjVenta() {
        return (Number)getAttributeInternal(IDEJVENTA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdEjVenta.
     * @param value value to set the IdEjVenta
     */
    public void setIdEjVenta(Number value) {
        setAttributeInternal(IDEJVENTA, value);
    }

    /**
     * Gets the attribute value for NomEjVenta, using the alias name NomEjVenta.
     * @return the NomEjVenta
     */
    public String getNomEjVenta() {
        return (String)getAttributeInternal(NOMEJVENTA);
    }

    /**
     * Sets <code>value</code> as the attribute value for NomEjVenta.
     * @param value value to set the NomEjVenta
     */
    public void setNomEjVenta(String value) {
        setAttributeInternal(NOMEJVENTA, value);
    }

    /**
     * Gets the attribute value for IdCanal, using the alias name IdCanal.
     * @return the IdCanal
     */
    public Number getIdCanal() {
        return (Number)getAttributeInternal(IDCANAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdCanal.
     * @param value value to set the IdCanal
     */
    public void setIdCanal(Number value) {
        setAttributeInternal(IDCANAL, value);
    }

    /**
     * Gets the attribute value for NomCanal, using the alias name NomCanal.
     * @return the NomCanal
     */
    public String getNomCanal() {
        return (String)getAttributeInternal(NOMCANAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for NomCanal.
     * @param value value to set the NomCanal
     */
    public void setNomCanal(String value) {
        setAttributeInternal(NOMCANAL, value);
    }

    /**
     * Gets the attribute value for Cantidad, using the alias name Cantidad.
     * @return the Cantidad
     */
    public Number getCantidad() {
        return (Number)getAttributeInternal(CANTIDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cantidad.
     * @param value value to set the Cantidad
     */
    public void setCantidad(Number value) {
        
        ADFContext ctx = ADFContext.getCurrent();
        
        Number por = new Number(0);
        Double porcentaje =0.0;
        Double cantidad =0.0;
        Double total = 0.0; 

      String totalAsignado = 
            ctx.getSessionScope().get("Cantidad") == null ? "" : ctx.getSessionScope().get("Cantidad").toString();
      
        total = Double.parseDouble(totalAsignado);
        
        if(total != 0){
            
        cantidad = Double.parseDouble(value.toString());
            
        porcentaje = Math.floor(((cantidad*100)/total)* 100.0) / 100.0;
            
            
        

        try {
             por = new Number(porcentaje);
            
        } catch (SQLException e) {
        }
        }          
                
        setAttributeInternal(CANTIDAD, value);
        setAttributeInternal(PORCASIG, por);
        
    }

    /**
     * Gets the attribute value for PorcAsig, using the alias name PorcAsig.
     * @return the PorcAsig
     */
    public Number getPorcAsig() {
        return (Number)getAttributeInternal(PORCASIG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PorcAsig.
     * @param value value to set the PorcAsig
     */
    public void setPorcAsig(Number value) {
        ADFContext ctx = ADFContext.getCurrent();
          
        Number cant = new Number(0);
        Double porcentaje =0.0;
        Double cantidad =0.0;
        Double total = 0.0; 
        
        String totalAsignado =
            ctx.getSessionScope().get("Cantidad") == null ? "" : ctx.getSessionScope().get("Cantidad").toString();
        
        System.out.println(totalAsignado + "TOTAL ASIG");
        
        
        total = Double.parseDouble(totalAsignado);
        if(total != 0){
        System.out.println(total + "AAAAAAAAAA");
        porcentaje = Double.parseDouble(value.toString());
            System.out.println(porcentaje + "BBBBBBBB");
        cantidad = Math.floor(((total*porcentaje)/100))*10.0/10.0;        
            System.out.println(cantidad + "CCCCCCCCCCc");
        
        
        try {
             cant = new Number(cantidad);
            
        } catch (SQLException e) {
        }
        }    
        setAttributeInternal(CANTIDAD, cant);
        setAttributeInternal(PORCASIG, value);
    }


    /**
     * Gets the attribute value for IdTbl, using the alias name IdTbl.
     * @return the IdTbl
     */
    public Number getIdTbl() {
        return (Number)getAttributeInternal(IDTBL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdTbl.
     * @param value value to set the IdTbl
     */
    public void setIdTbl(Number value) {
        setAttributeInternal(IDTBL, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param idTbl key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idTbl) {
        return new Key(new Object[]{idTbl});
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
