package eo;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;

import utils.CustomEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 22 11:37:15 COT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbpSlsOptyColImpl extends CustomEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdOptyCol {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getIdOptyCol();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setIdOptyCol((Number)value);
            }
        }
        ,
        OptyColumn {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getOptyColumn();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setOptyColumn((String)value);
            }
        }
        ,
        Estado {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getEstado();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setEstado((String)value);
            }
        }
        ,
        NroOrden {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getNroOrden();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setNroOrden((Number)value);
            }
        }
        ,
        CodCol {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getCodCol();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setCodCol((String)value);
            }
        }
        ,
        NomOrCol {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getNomOrCol();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setNomOrCol((String)value);
            }
        }
        ,
        NomTab {
            public Object get(SbpSlsOptyColImpl obj) {
                return obj.getNomTab();
            }

            public void put(SbpSlsOptyColImpl obj, Object value) {
                obj.setNomTab((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(SbpSlsOptyColImpl object);

        public abstract void put(SbpSlsOptyColImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDOPTYCOL = AttributesEnum.IdOptyCol.index();
    public static final int OPTYCOLUMN = AttributesEnum.OptyColumn.index();
    public static final int ESTADO = AttributesEnum.Estado.index();
    public static final int NROORDEN = AttributesEnum.NroOrden.index();
    public static final int CODCOL = AttributesEnum.CodCol.index();
    public static final int NOMORCOL = AttributesEnum.NomOrCol.index();
    public static final int NOMTAB = AttributesEnum.NomTab.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SbpSlsOptyColImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("eo.SbpSlsOptyCol");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for IdOptyCol, using the alias name IdOptyCol.
     * @return the IdOptyCol
     */
    public Number getIdOptyCol() {
        return (Number)getAttributeInternal(IDOPTYCOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdOptyCol.
     * @param value value to set the IdOptyCol
     */
    public void setIdOptyCol(Number value) {
        setAttributeInternal(IDOPTYCOL, value);
    }

    /**
     * Gets the attribute value for OptyColumn, using the alias name OptyColumn.
     * @return the OptyColumn
     */
    public String getOptyColumn() {
        return (String)getAttributeInternal(OPTYCOLUMN);
    }

    /**
     * Sets <code>value</code> as the attribute value for OptyColumn.
     * @param value value to set the OptyColumn
     */
    public void setOptyColumn(String value) {
        setAttributeInternal(OPTYCOLUMN, value);
    }

    /**
     * Gets the attribute value for Estado, using the alias name Estado.
     * @return the Estado
     */
    public String getEstado() {
        return (String)getAttributeInternal(ESTADO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Estado.
     * @param value value to set the Estado
     */
    public void setEstado(String value) {
        setAttributeInternal(ESTADO, value);
    }

    /**
     * Gets the attribute value for NroOrden, using the alias name NroOrden.
     * @return the NroOrden
     */
    public Number getNroOrden() {
        return (Number)getAttributeInternal(NROORDEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for NroOrden.
     * @param value value to set the NroOrden
     */
    public void setNroOrden(Number value) {
        setAttributeInternal(NROORDEN, value);
    }

    /**
     * Gets the attribute value for CodCol, using the alias name CodCol.
     * @return the CodCol
     */
    public String getCodCol() {
        return (String)getAttributeInternal(CODCOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodCol.
     * @param value value to set the CodCol
     */
    public void setCodCol(String value) {
        setAttributeInternal(CODCOL, value);
    }

    /**
     * Gets the attribute value for NomOrCol, using the alias name NomOrCol.
     * @return the NomOrCol
     */
    public String getNomOrCol() {
        return (String)getAttributeInternal(NOMORCOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for NomOrCol.
     * @param value value to set the NomOrCol
     */
    public void setNomOrCol(String value) {
        setAttributeInternal(NOMORCOL, value);
    }

    /**
     * Gets the attribute value for NomTab, using the alias name NomTab.
     * @return the NomTab
     */
    public String getNomTab() {
        return (String)getAttributeInternal(NOMTAB);
    }

    /**
     * Sets <code>value</code> as the attribute value for NomTab.
     * @param value value to set the NomTab
     */
    public void setNomTab(String value) {
        setAttributeInternal(NOMTAB, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param idOptyCol key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idOptyCol) {
        return new Key(new Object[]{idOptyCol});
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
